#!/bin/bash

# Check that the script is run with “sudo” permission.
if [ "$USER" != "root" ]; then
    echo "This script must be run as using sudo (as root user)."
    exit 1
fi

#------------------------------------------- Checking Arguments and assigning them -------------------------------------#

# Check that these arguments are really passed (i.e. they are not empty).
if [ $# -ne 3 ]; then
#if any argument wasn’t passed, print a message and exit with failed status
    echo "You should pass 3 arguments when you run the script: <username> <userpass> <groupname>"
    exit 1
fi

# Assign arguments to variables
USERNAME=$1
USERPASS=$2
GROUPNAME=$3

# Print the entered arguments
echo "Username: $USERNAME"
echo "Password: $USERPASS"
echo "Group Name: $GROUPNAME"

#------------------------------------------- Creating a user -------------------------------------#

# Create this new user, with these conditions:
#	• Its name should be taken from the argument
#	• Create a home directory for this user
#	• Assign the default shell as “Bash”
#	• Do not create a group with the same name
useradd -m -d /home/$USERNAME -s /bin/bash $USERNAME
if [ $? -ne 0 ]; then
    echo "Failed to create user $USERNAME"
    exit 1
fi

# Assign a password for this new user without prompting on the display
echo "$USERNAME:$USERPASS" | chpasswd
if [ $? -ne 0 ]; then
    echo "Failed to set password for user $USERNAME"
    exit 1
fi

# Display the user and group information about this user
echo "User information after creating the user:"
id $USERNAME

#------------------------------------------- Assigning the user to a group --------------------------------------#

# Create a new group with ID=200
groupadd -g 200 $GROUPNAME
if [ $? -ne 0 ]; then
    echo "Failed to create the group $GROUPNAME with GID=200"
    exit 1
fi

# Add the new user to the newly made group (GID=200)
usermod -aG $GROUPNAME $USERNAME
if [ $? -ne 0 ]; then
    echo "Failed to add user $USERNAME to group $GROUPNAME"
    exit 1
fi

# Display user and group information after adding to group
echo "User and group information after adding to group $GROUPNAME:"
id $USERNAME

#------------------------------------------- Modifying the user ID and its primary group -------------------------------------#

# Modify the user to have UID=1600 and change primary group to $GROUPNAME
usermod -u 1600 -g $GROUPNAME $USERNAME
if [ $? -ne 0 ]; then
    echo "Failed to modify user $USERNAME"
    exit 1
fi

# Display user information after modifying the user ID and its primary group
echo "User and group information after modifying the user ID and its primary group:"
id $USERNAME

echo "User $USERNAME created and modified successfully."
